version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: meuusuario
      MONGO_INITDB_ROOT_PASSWORD: minhasenha
      MONGO_INITDB_DATABASE: meubanco
    ports:
      - "27017:27017"
